In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
df = pd.read_csv("animalId-760-farmId-66 2024-11-29T18_43 2025-10-27T17_43.csv")
df

,date,event,temp,airTemp,humidity,accel,rumination,waterTemp,ageInDays,lactationNumber,aveHerdTemp
0,2024-11-29 18:43:36,NaN,39.0,1.2,71.6,0.08,0.0,NaN,2,0,NaN
1,2024-11-29 18:58:36,NaN,39.0,1.1,74.6,0.09,0.0,NaN,2,0,NaN
2,2024-11-29 19:13:36,NaN,39.0,1.1,73.5,0.07,1.0,NaN,2,0,39.19
3,2024-11-29 19:28:36,NaN,39.1,1.1,73.5,0.08,0.0,NaN,2,0,NaN
4,2024-11-29 19:43:36,NaN,39.2,0.9,75.1,0.08,0.0,NaN,2,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
30608,2025-10-27 12:15:23,NaN,39.3,3.8,76.5,0.32,1.0,NaN,334,0,NaN
30609,2025-10-27 12:30:23,NaN,39.3,3.8,75.6,0.23,0.0,NaN,334,0,NaN
30610,2025-10-27 12:45:23,NaN,39.2,4.1,75.4,0.13,0.0,NaN,334,0,NaN
30611,2025-10-27 13:00:23,NaN,39.2,4.6,77.1,NaN,NaN,NaN,334,0,NaN
30612,2025-10-27 13:15:23,NaN,39.2,4.6,77.1,NaN,NaN,NaN,334,0,NaN

In [18]:
df = df.drop(columns=['waterTemp','lactationNumber'])

In [19]:
df.head()

,date,event,temp,airTemp,humidity,accel,rumination,ageInDays,aveHerdTemp
0,2024-11-29 18:43:36,NaN,39.0,1.2,71.6,0.08,0.0,2,NaN
1,2024-11-29 18:58:36,NaN,39.0,1.1,74.6,0.09,0.0,2,NaN
2,2024-11-29 19:13:36,NaN,39.0,1.1,73.5,0.07,1.0,2,39.19
3,2024-11-29 19:28:36,NaN,39.1,1.1,73.5,0.08,0.0,2,NaN
4,2024-11-29 19:43:36,NaN,39.2,0.9,75.1,0.08,0.0,2,NaN

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30613 entries, 0 to 30612
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         30613 non-null  object
 1   event        2 non-null      object
 2   temp         30613 non-null  float64
 3   airTemp      30444 non-null  float64
 4   humidity     30444 non-null  float64
 5   accel        29677 non-null  float64
 6   rumination   29677 non-null  float64
 7   ageInDays    30613 non-null  int64
 8   aveHerdTemp  7558 non-null   float64
dtypes: float64(6), int64(1), object(2)
memory usage: 2.1+ MB

In [21]:
df['date']

0        2024-11-29 18:43:36
1        2024-11-29 18:58:36
2        2024-11-29 19:13:36
3        2024-11-29 19:28:36
4        2024-11-29 19:43:36
                ...
30608    2025-10-27 12:15:23
30609    2025-10-27 12:30:23
30610    2025-10-27 12:45:23
30611    2025-10-27 13:00:23
30612    2025-10-27 13:15:23
Name: date, Length: 30613, dtype: object

In [22]:
df.rename(columns={'date':'datetime'}, inplace=True)

In [23]:
df['datetime'] = pd.to_datetime(df['datetime'])

df['date'] = pd.to_datetime(df['datetime']).dt.date
df['time'] = pd.to_datetime(df['datetime']).dt.time

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30613 entries, 0 to 30612
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   datetime     30613 non-null  datetime64[ns]
 1   event        2 non-null      object
 2   temp         30613 non-null  float64
 3   airTemp      30444 non-null  float64
 4   humidity     30444 non-null  float64
 5   accel        29677 non-null  float64
 6   rumination   29677 non-null  float64
 7   ageInDays    30613 non-null  int64
 8   aveHerdTemp  7558 non-null   float64
 9   date         30613 non-null  object
 10  time         30613 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 2.6+ MB

In [25]:
mean_air_temp = df['airTemp'].mean()

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30613 entries, 0 to 30612
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   datetime     30613 non-null  datetime64[ns]
 1   event        2 non-null      object
 2   temp         30613 non-null  float64
 3   airTemp      30444 non-null  float64
 4   humidity     30444 non-null  float64
 5   accel        29677 non-null  float64
 6   rumination   29677 non-null  float64
 7   ageInDays    30613 non-null  int64
 8   aveHerdTemp  7558 non-null   float64
 9   date         30613 non-null  object
 10  time         30613 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 2.6+ MB

In [27]:
df['airTemp'] = df['airTemp'].interpolate(method='linear')
df['humidity'] = df['humidity'].interpolate(method='linear')
df['accel'] = df['accel'].interpolate(method='linear')

In [ ]:

df['rumination'] = df['rumination'].interpolate(method='nearest')

df['rumination'] = df['rumination'].fillna(0)

df['rumination'] = df['rumination'].round().astype(int)

In [29]:
df

,datetime,event,temp,airTemp,humidity,accel,rumination,ageInDays,aveHerdTemp,date,time
0,2024-11-29 18:43:36,NaN,39.0,1.2,71.6,0.08,0,2,NaN,2024-11-29,18:43:36
1,2024-11-29 18:58:36,NaN,39.0,1.1,74.6,0.09,0,2,NaN,2024-11-29,18:58:36
2,2024-11-29 19:13:36,NaN,39.0,1.1,73.5,0.07,1,2,39.19,2024-11-29,19:13:36
3,2024-11-29 19:28:36,NaN,39.1,1.1,73.5,0.08,0,2,NaN,2024-11-29,19:28:36
4,2024-11-29 19:43:36,NaN,39.2,0.9,75.1,0.08,0,2,NaN,2024-11-29,19:43:36
...,...,...,...,...,...,...,...,...,...,...,...
30608,2025-10-27 12:15:23,NaN,39.3,3.8,76.5,0.32,1,334,NaN,2025-10-27,12:15:23
30609,2025-10-27 12:30:23,NaN,39.3,3.8,75.6,0.23,0,334,NaN,2025-10-27,12:30:23
30610,2025-10-27 12:45:23,NaN,39.2,4.1,75.4,0.13,0,334,NaN,2025-10-27,12:45:23
30611,2025-10-27 13:00:23,NaN,39.2,4.6,77.1,0.13,0,334,NaN,2025-10-27,13:00:23
30612,2025-10-27 13:15:23,NaN,39.2,4.6,77.1,0.13,0,334,NaN,2025-10-27,13:15:23

In [30]:
check_null = df.isna().sum()
check_null

datetime           0
event          30611
temp               0
airTemp            0
humidity           0
accel              0
rumination         0
ageInDays          0
aveHerdTemp    23055
date               0
time               0
dtype: int64

## Visualizations

In [31]:
import plotly.graph_objects as go

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30613 entries, 0 to 30612
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   datetime     30613 non-null  datetime64[ns]
 1   event        2 non-null      object
 2   temp         30613 non-null  float64
 3   airTemp      30613 non-null  float64
 4   humidity     30613 non-null  float64
 5   accel        30613 non-null  float64
 6   rumination   30613 non-null  int32
 7   ageInDays    30613 non-null  int64
 8   aveHerdTemp  7558 non-null   float64
 9   date         30613 non-null  object
 10  time         30613 non-null  object
dtypes: datetime64[ns](1), float64(5), int32(1), int64(1), object(3)
memory usage: 2.5+ MB

In [ ]:
fig = go.Figure()


fig.add_trace(go.Scatter(
    x=df['datetime'],
    y=df['temp'],
    mode='lines+markers',
    name='Calf Temp (°C)',
    line=dict(color='orange', width=2),
    marker=dict(size=3)
))


fig.add_trace(go.Scatter(
    x=df['datetime'],
    y=df['airTemp'],
    mode='lines+markers',
    name='Outside Air Temp (°C)',
    line=dict(color='skyblue', width=2, dash='dot'),
    marker=dict(size=3)
))

fig.update_layout(
    title='Calf vs Outside Temperature Over Time',
    xaxis_title='Date & Time',
    yaxis_title='Temperature (°C)',
    legend_title='Temperature Type',
    template='plotly_dark',  
    hovermode='x unified',
    xaxis=dict(showgrid=False),
    yaxis=dict(showgrid=True, gridcolor='gray'),
    title_font=dict(size=20, family='Arial', color='white')
)

fig.show()

In [35]:
df['datetime'].unique()

<DatetimeArray>
['2024-11-29 18:43:36', '2024-11-29 18:58:36', '2024-11-29 19:13:36',
 '2024-11-29 19:28:36', '2024-11-29 19:43:36', '2024-11-29 19:58:36',
 '2024-11-29 20:13:36', '2024-11-29 20:28:36', '2024-11-29 20:43:36',
 '2024-11-29 20:58:36',
 ...
 '2025-10-27 11:00:23', '2025-10-27 11:15:23', '2025-10-27 11:30:23',
 '2025-10-27 11:45:23', '2025-10-27 12:00:23', '2025-10-27 12:15:23',
 '2025-10-27 12:30:23', '2025-10-27 12:45:23', '2025-10-27 13:00:23',
 '2025-10-27 13:15:23']
Length: 30613, dtype: datetime64[ns]

In [ ]:
df['month'] = df['datetime'].dt.month


df_summer = df[df['month'].isin([5, 6, 7, 8])]   # May–Aug
df_winter = df[df['month'].isin([11, 12, 1, 2])] # Nov–Feb


def create_temp_plot(data, season_name, color1='orange', color2='skyblue'):
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=data['datetime'],
        y=data['temp'],
        mode='lines',
        name='Calf Temp (°C)',
        line=dict(color=color1, width=2)
    ))

    fig.add_trace(go.Scatter(
        x=data['datetime'],
        y=data['airTemp'],
        mode='lines',
        name='Outside Air Temp (°C)',
        line=dict(color=color2, width=2, dash='dot')
    ))

    fig.update_layout(
        title=f'Calf vs Outside Temperature — {season_name}',
        xaxis_title='Date & Time',
        yaxis_title='Temperature (°C)',
        legend_title='Temperature Type',
        template='plotly_dark',
        hovermode='x unified',
        xaxis=dict(showgrid=False),
        yaxis=dict(showgrid=True, gridcolor='gray'),
        title_font=dict(size=20, family='Arial', color='white')
    )
    return fig


fig_summer = create_temp_plot(df_summer, "Peak Summer (May–Aug)")
fig_winter = create_temp_plot(df_winter, "Peak Winter (Nov–Feb)")

fig_summer.show()
fig_winter.show()

In [37]:
new_df = df.copy()

In [38]:
new_df.to_csv("cleaned-animalId-760-farmId-66 2024-11-29T18_43 2025-10-27T17_43.csv")

In [39]:
new_df.head()

,datetime,event,temp,airTemp,humidity,accel,rumination,ageInDays,aveHerdTemp,date,time,month
0,2024-11-29 18:43:36,NaN,39.0,1.2,71.6,0.08,0,2,NaN,2024-11-29,18:43:36,11
1,2024-11-29 18:58:36,NaN,39.0,1.1,74.6,0.09,0,2,NaN,2024-11-29,18:58:36,11
2,2024-11-29 19:13:36,NaN,39.0,1.1,73.5,0.07,1,2,39.19,2024-11-29,19:13:36,11
3,2024-11-29 19:28:36,NaN,39.1,1.1,73.5,0.08,0,2,NaN,2024-11-29,19:28:36,11
4,2024-11-29 19:43:36,NaN,39.2,0.9,75.1,0.08,0,2,NaN,2024-11-29,19:43:36,11

In [40]:
df['month'] = df['datetime'].dt.month


df_summer = df[df['month'].isin([5, 6, 7, 8])]
df_winter = df[df['month'].isin([11, 12, 1, 2])]


TEMP_THRESHOLD = 39.8
THI_THRESHOLD = 74  

def create_temp_plot(data, season_name, color1='orange', color2='skyblue', color3='lightgreen'):
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=data['datetime'],
        y=data['temp'],
        mode='lines',
        name='Calf Temp (°C)',
        line=dict(color=color1, width=2)
    ))

    
    fig.add_trace(go.Scatter(
        x=data['datetime'],
        y=data['airTemp'],
        mode='lines',
        name='Outside Air Temp (°C)',
        line=dict(color=color2, width=2, dash='dot')
    ))

    fig.add_trace(go.Scatter(
        x=data['datetime'],
        y=data['humidity'],
        mode='lines',
        name='Humidity / THI',
        yaxis='y2',
        line=dict(color=color3, width=2, dash='dash')
    ))

    
    stress_points = data[(data['temp'] > TEMP_THRESHOLD) & (data['humidity'] > THI_THRESHOLD)]
    fig.add_trace(go.Scatter(
        x=stress_points['datetime'],
        y=stress_points['temp'],
        mode='markers',
        name='⚠️ Heat Stress',
        marker=dict(color='red', size=8, symbol='circle'),
        hovertext=[f"THI={h:.1f}" for h in stress_points['humidity']]
    ))

    
    fig.update_layout(
        title=f'Calf Temp, Air Temp & Humidity (THI) — {season_name}',
        xaxis_title='Date & Time',
        yaxis_title='Temperature (°C)',
        legend_title='Metrics',
        template='plotly_dark',
        hovermode='x unified',
        xaxis=dict(showgrid=False),
        yaxis=dict(showgrid=True, gridcolor='gray'),

    
        yaxis2=dict(
            title='Humidity / THI',
            overlaying='y',
            side='right',
            showgrid=False
        ),
        title_font=dict(size=20, family='Arial', color='white')
    )

    return fig


fig_summer = create_temp_plot(df_summer, "Peak Summer (May–Aug)")
fig_winter = create_temp_plot(df_winter, "Peak Winter (Nov–Feb)")


fig_summer.show()
fig_winter.show()